### ISSUE TITLE
Conferences attended by alumni show up on new teams

### ISSUE THREAD

**Issue by Althaire** [rails-girls-summer-of-code/rgsoc-teams#473]
I just checked the team I am supervising this year and my conferences from last year as an attendee show up under the conferences section for them:
![screen shot 2016-06-27 at 20 22 00](https://cloud.githubusercontent.com/assets/5068494/16390894/11c6719c-3ca5-11e6-8019-335457233a7d.png)

I'm going to remove them from my profile to avoid any confusion for now.
_EDIT: don't know how to remove them, so they're there_

This bug could be encountered very little but it might get increasingly confusing if people from previous years stay on 🐙

**Comment by carpodaster** [comment]
Thanks @Althaire for reporting this. Yes, that's a solid bug and actually occurs more often than we would think: luckily there are many alumni who stay loyal to the program and find themselves back in RGSoC in roles other than students 😉

**Comment by mkalininait** [comment]
@Althaire I've removed those conferences 2015 from your profile. Hope it is ok with you :)

@carpodaster @F3PiX I'm not sure, can we close this issue? Was is resolved with this PR https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/494 ? AFAIU, we still need to remove conferences 2015 manually in cases like this one, right?

**Comment by carpodaster** [comment]
@mkalininait no, it's not fixed. I was planning to get to it tonight or tomorrow :)

**Comment by mkalininait** [comment]
@carpodaster Ah, I see. 
I guess I spoiled a good case by deleting those conferences from @Althaire 's profile then /facepalm/ Sorry :(
